import { z } from "zod";
import { router, publicProcedure, adminProcedure } from "../_core/trpc";
import { db } from "../db";
import { newsPosts, starsOfWeek, users, teams } from "../../shared/schema";
import { eq, desc, and } from "drizzle-orm";

export const contentRouter = router({
  // Public: published news posts, newest first
  newsFeed: publicProcedure.query(async () => {
    return db
      .select()
      .from(newsPosts)
      .where(eq(newsPosts.status, "published"))
      .orderBy(desc(newsPosts.publishedAt));
  }),

  // Public: a single published post by id
  newsPost: publicProcedure
    .input(z.object({ id: z.number() }))
    .query(async ({ input }) => {
      const [post] = await db
        .select()
        .from(newsPosts)
        .where(and(eq(newsPosts.id, input.id), eq(newsPosts.status, "published")));
      return post ?? null;
    }),

  // Public: most recent approved Stars of the Week
  currentStars: publicProcedure.query(async () => {
    return db
      .select({
        star: starsOfWeek,
        player: { id: users.id, firstName: users.firstName, lastName: users.lastName },
        team: teams,
      })
      .from(starsOfWeek)
      .innerJoin(users, eq(starsOfWeek.playerUserId, users.id))
      .leftJoin(teams, eq(starsOfWeek.teamId, teams.id))
      .where(eq(starsOfWeek.status, "approved"))
      .orderBy(desc(starsOfWeek.weekStartDate));
  }),

  // Admin: list draft posts awaiting review (auto-generated weekly recap, etc.)
  listDraftPosts: adminProcedure.query(async () => {
    return db.select().from(newsPosts).where(eq(newsPosts.status, "draft"));
  }),

  // Admin: publish a draft post as-is or after light editing
  publishPost: adminProcedure
    .input(z.object({ postId: z.number(), title: z.string().optional(), bodyHtml: z.string().optional() }))
    .mutation(async ({ input }) => {
      await db
        .update(newsPosts)
        .set({
          ...(input.title ? { title: input.title } : {}),
          ...(input.bodyHtml ? { bodyHtml: input.bodyHtml } : {}),
          status: "published",
          publishedAt: new Date(),
        })
        .where(eq(newsPosts.id, input.postId));
      return { success: true };
    }),

  // Admin: create a manual post directly
  createPost: adminProcedure
    .input(z.object({ title: z.string(), bodyHtml: z.string(), publishNow: z.boolean() }))
    .mutation(async ({ input, ctx }) => {
      await db.insert(newsPosts).values({
        title: input.title,
        bodyHtml: input.bodyHtml,
        isAutoGenerated: false,
        status: input.publishNow ? "published" : "draft",
        publishedAt: input.publishNow ? new Date() : undefined,
        authorUserId: ctx.user.id,
      });
      return { success: true };
    }),

  // Admin: this week's draft Stars of the Week pick, awaiting approval/edit
  draftStars: adminProcedure.query(async () => {
    return db
      .select({
        star: starsOfWeek,
        player: { id: users.id, firstName: users.firstName, lastName: users.lastName },
        team: teams,
      })
      .from(starsOfWeek)
      .innerJoin(users, eq(starsOfWeek.playerUserId, users.id))
      .leftJoin(teams, eq(starsOfWeek.teamId, teams.id))
      .where(eq(starsOfWeek.status, "draft"));
  }),

  // Admin: change the auto-picked player before approving
  changeStarPlayer: adminProcedure
    .input(z.object({ starId: z.number(), playerUserId: z.number(), teamId: z.number().optional() }))
    .mutation(async ({ input }) => {
      await db
        .update(starsOfWeek)
        .set({ playerUserId: input.playerUserId, teamId: input.teamId })
        .where(eq(starsOfWeek.id, input.starId));
      return { success: true };
    }),

  // Admin: approve (1-click) the draft Stars of the Week post
  approveStars: adminProcedure
    .input(z.object({ starId: z.number() }))
    .mutation(async ({ input, ctx }) => {
      await db
        .update(starsOfWeek)
        .set({ status: "approved", approvedAt: new Date(), approvedByUserId: ctx.user.id })
        .where(eq(starsOfWeek.id, input.starId));
      return { success: true };
    }),
});
