import "dotenv/config";
import { db, pool } from "../db";
import { games, teams, gameStats, users, newsPosts, starsOfWeek } from "../../shared/schema";
import { and, gte, lte, eq } from "drizzle-orm";

// Runs weekly via cPanel Cron Jobs, targeted for Sunday.
// It DRAFTS content only -- nothing is published or shown publicly until
// an admin reviews and publishes/approves it from the admin panel.

function startOfWeek(): Date {
  const now = new Date();
  const day = now.getDay(); // 0 = Sunday
  const diff = now.getDate() - day - 6; // previous Monday
  const monday = new Date(now);
  monday.setDate(diff);
  monday.setHours(0, 0, 0, 0);
  return monday;
}

async function draftWeeklyRecap() {
  const weekStart = startOfWeek();
  const weekStartStr = weekStart.toISOString().slice(0, 10);
  const todayDate = new Date();

  const finishedGames = await db
    .select({ game: games, homeTeam: teams })
    .from(games)
    .leftJoin(teams, eq(games.homeTeamId, teams.id))
    .where(
      and(
        eq(games.status, "final"),
        gte(games.gameDate, weekStart),
        lte(games.gameDate, todayDate)
      )
    );

  if (finishedGames.length === 0) {
    console.log("No finalized games this week -- skipping recap draft.");
    return;
  }

  const allTeams = await db.select().from(teams);
  const teamName = (id: number | null) => allTeams.find((t) => t.id === id)?.name ?? "TBD";

  const lines = finishedGames.map(({ game }) => {
    return `${teamName(game.homeTeamId)} ${game.homeScore} - ${game.awayScore} ${teamName(game.awayTeamId)}`;
  });

  const bodyHtml = `
    <p>Here's how the games went this week:</p>
    <ul>${lines.map((l) => `<li>${l}</li>`).join("")}</ul>
  `;

  await db.insert(newsPosts).values({
    title: `Weekly Recap -- Week of ${weekStartStr}`,
    bodyHtml,
    isAutoGenerated: true,
    status: "draft",
  });

  console.log(`Drafted weekly recap post with ${finishedGames.length} games.`);
}

async function draftStarsOfWeek() {
  const weekStart = startOfWeek();
  const weekStartStr = weekStart.toISOString().slice(0, 10);
  const todayDate = new Date();

  const weekGames = await db
    .select({ id: games.id })
    .from(games)
    .where(
      and(
        eq(games.status, "final"),
        gte(games.gameDate, weekStart),
        lte(games.gameDate, todayDate)
      )
    );

  if (weekGames.length === 0) {
    console.log("No finalized games this week -- skipping Stars of the Week draft.");
    return;
  }

  const gameIds = weekGames.map((g) => g.id);
  const weekStats = await db.select().from(gameStats);
  const relevant = weekStats.filter((s) => gameIds.includes(s.gameId));

  const byPlayer = new Map<number, { points: number; teamId: number }>();
  for (const s of relevant) {
    const entry = byPlayer.get(s.playerUserId) ?? { points: 0, teamId: s.teamId };
    entry.points += s.goals + s.assists;
    byPlayer.set(s.playerUserId, entry);
  }

  if (byPlayer.size === 0) {
    console.log("No stats recorded this week -- skipping Stars of the Week draft.");
    return;
  }

  const [topPlayerId, topStats] = Array.from(byPlayer.entries()).sort(
    (a, b) => b[1].points - a[1].points
  )[0];

  const [player] = await db.select().from(users).where(eq(users.id, topPlayerId));

  await db.insert(starsOfWeek).values({
    weekStartDate: weekStart,
    playerUserId: topPlayerId,
    teamId: topStats.teamId,
    note: `${topStats.points} points this week`,
    status: "draft",
  });

  console.log(`Drafted Stars of the Week: ${player?.firstName} ${player?.lastName}`);
}

async function run() {
  await draftWeeklyRecap();
  await draftStarsOfWeek();
  await pool.end();
}

run().catch((err) => {
  console.error("Weekly digest failed:", err);
  process.exit(1);
});
